# Generated by Django 5.0.1 on 2024-03-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_latitude_user_longitude_user_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='willing_to_adopt',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
