# Generated by Django 5.0.1 on 2024-03-03 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='adoption')),
                ('description', models.CharField(max_length=1024)),
                ('created_at', models.DateField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('latitude', models.CharField(blank=True, max_length=250, null=True)),
                ('longitude', models.CharField(blank=True, max_length=250, null=True)),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='adoption_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_request', models.CharField(default='active', max_length=50)),
                ('adoption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.adoption')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Map_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('place_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_dogs', models.IntegerField(blank=True, null=True)),
                ('behaviour', models.CharField(blank=True, max_length=255, null=True)),
                ('zone', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=50)),
                ('radius_color', models.CharField(choices=[('#FF0000', 'Red'), ('#FFD326', 'Yellow'), ('#2AAD27', 'Green')], max_length=50)),
                ('radius_color_hexcode', models.CharField(choices=[('#FF0000', 'Red'), ('#FFD326', 'Yellow'), ('#2AAD27', 'Green')], max_length=50)),
                ('km_distance', models.IntegerField(choices=[('250', '500 Meters'), ('500', '1 Km'), ('1000', '2 Km'), ('1500', '3 Km'), ('2000', '4 Km'), ('2500', '5 Km')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog_Pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.map_details')),
            ],
        ),
        migrations.CreateModel(
            name='missing_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=250, null=True)),
                ('place', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_no', models.IntegerField()),
                ('breed', models.CharField(blank=True, max_length=250, null=True)),
                ('color', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('status', models.CharField(default='active', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('missing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.missing_case')),
            ],
        ),
        migrations.CreateModel(
            name='missing_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('report_summery', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True)),
                ('missing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.missing_case')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
