# Generated by Django 5.0.1 on 2024-03-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adoption',
            name='dog_license',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.AddField(
            model_name='adoption',
            name='vaccination',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
