# Generated by Django 5.0.1 on 2024-02-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='missing_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=250)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
