# Generated by Django 5.0.1 on 2024-02-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_missing_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_case',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
