# Generated by Django 5.0.1 on 2024-03-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_adoption_age_adoption_dog_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_case',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
