# Generated by Django 5.0.1 on 2024-02-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_missing_case_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_case',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
