# Generated by Django 5.0.1 on 2024-02-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_missing_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing_case',
            name='status',
            field=models.CharField(default='active', max_length=50, null=True),
        ),
    ]
