# Generated by Django 5.0.1 on 2024-02-04 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_missing_case_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True)),
                ('missing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.missing_case')),
            ],
        ),
    ]
