# Generated by Django 5.0.1 on 2024-02-16 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='missing_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('report_summery', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True)),
                ('missing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.missing_case')),
            ],
        ),
    ]
