# Generated by Django 5.0.1 on 2024-03-01 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_missing_case_breed_missing_case_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='adoption')),
                ('description', models.CharField(max_length=1024)),
                ('created_at', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('latitude', models.CharField(blank=True, max_length=250, null=True)),
                ('longitude', models.CharField(blank=True, max_length=250, null=True)),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
