# Generated by Django 5.0.1 on 2024-03-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_adoption_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing_case',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
