from django.urls import path

from user.views import *

urlpatterns = [
    path('dashboard/', dashboard, name='user.dashboard'),
    path('map-view/', map_view, name='user.map_view'),
    path('map-maker/', static_dogspot_marker_map, name='user.static_dogspot_marker_map'),
    path('add-dogspot/<str:lat>/<str:lng>/', add_dogspot, name='user.add_dogspot'),
    path('missing_form/',missings_form,name='user.missings_form'),
    path('missings/',missings, name='user.missings'),
    path('missing_details/<pk>',missing_details,name='user.missing_details'),
    path('edit/<pk>',edit,name='user.missing_edit'),
    path('delete/<pk>',delete,name='user.missing_delete'),
    path('comment/<pk>',comment_view,name='user.comment_view'),
    path('comment_dele/<pk>',comment_delete,name='user.comment_delete'),
    path('report/<pk>',missing_rpt,name='user.missing_rpt'),
    path('report_case/<pk>',report_case,name='user.report_case'),
    path('report_list/',report_list,name='user.report_list'),
    path('report_delete/<pk>',report_delete,name='user.report_delete'),
    path('profile/',profile,name='user.profile'),
    path('profile_update/',profile_edit,name='user.profile_edit'),
    path('adoption_form/',adoption_form,name='user.adoption_form'),
    path('adoption/',adoption_view,name='user.adoption_view'),
    path('adoption_edit/<pk>',edit_adoption,name='user.edit_adoption'),
    path('adoption_detail/<pk>',adoption_details,name='user.adoption_details'),
    path('adoption_delete/<pk>',adoption_delete,name='user.adoption_delete'),
    path('adoption_req_snd/',adoption_snd_view,name='user.adoption_snd_view'),
    path('adoption_snd_details/<pk>',adoption_snd_details,name='user.adoption_snd_details'),
    path('adp_request_list/<pk>', request_list,name='user.request_list'),
    path('request_profile/<pk>', request_profile,name='user.request_profile'),
    path('request_cancel/<pk>', request_cancel,name='user.request_cancel'),
    path('request_send/<pk>', request_send,name='user.request_send'),
    path('received_list/', received_list,name='user.received_list'),
    path('request_accept/<pk>', request_accept,name='user.request_accept'),
    path('request_reject/<pk>', request_reject,name='user.request_reject'),
    path('recived_cancel/<pk>', recived_cancel,name='user.recived_cancel'),
    path('dogspot_list/', dogspot_list, name='user.dogspot_list'),
    path('dogspot_update/', dogspot_update, name='user.dogspot_update'),
    path('dogspot_delete/', dogspot_delete, name='user.dogspot_delete'),
]